// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/7/17 19:02:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/wuliangyu/Downloads/ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/plugins/**/*.{js,ts,mjs}","/Users/wuliangyu/Downloads/ai/composables/**/*.{js,ts,mjs}","/Users/wuliangyu/Downloads/ai/utils/**/*.{js,ts,mjs}","/Users/wuliangyu/Downloads/ai/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/wuliangyu/Downloads/ai/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;